#This is the template for What2Log Tools entries

# Meta data about this App entry
title = ""
author = ""
credits = [ "" ]
release.date = 2021-05-21
release.version = "Ash"
category = "" #Top level sidebar heading this page will appear under
tags = [ "" ]

# About this app
operating_system = [""]
default_installed = true #True or false only

# Additional References Go Here
references = [
  "blah",
  "blah2"
]

#Installation Info (install info is optional, some tools are part of base os)
[[app.install]]
txt = """
"""
img = "img0.png"
#continue as necessary

# App Info
[[app.info]]
txt = """
"""
img = "img1.png"

[[app.info]]
txt = """
"""
img = "img2.png"
#continue as necessary
