#This is the template for What2Log pages

title = ""
credits = [ "" ] # Use this for any special shoutouts, bear in mind that we already link to the GitHub history of the page, so please don't use this for contributors.
tags = [ "" ] # Tags are searchable per platform.
# Displayed at the top of the page, and also appears as the summary in search results
description = """\

"""

# Additional References Go Here
references = [
  "blah",
  "blah2"
]

# The text and image pairs that appear in the main body of the page
[[content]]
txt = """
"""
img = "img0.png" # optional

[[content]]
txt = """
"""
img = "img0.png"

#... continue as necessary
